/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 corot7bfiery.gltf 
Author: uperesito (https://sketchfab.com/uperesito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/corot-7b-fiery-32843a5eea174d7bb663ac1af710a215
Title: Corot 7b (Fiery)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('corot7bfiery/corot7bfiery.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Esfera_Mat_0.geometry} material={materials.material} />
      <mesh geometry={nodes.Esfera_Mat_0_1.geometry} material={materials.material} />
      <mesh geometry={nodes.Esfera_Mat_0_2.geometry} material={materials.material} />
      <mesh geometry={nodes.Esfera_Mat_0_3.geometry} material={materials.material} />
      <mesh geometry={nodes.Esfera_Mat_0_4.geometry} material={materials.material} />
      <mesh geometry={nodes.Esfera_Mat_0_5.geometry} material={materials.material} />
      <mesh geometry={nodes.Esfera_Mat_0_6.geometry} material={materials.material} />
      <mesh geometry={nodes.Esfera_Mat_0_7.geometry} material={materials.material} />
    </group>
  )
}

useGLTF.preload('/corot7bfiery.gltf')
