/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 kepler186f.gltf 
Author: uperesito (https://sketchfab.com/uperesito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kepler-186f-c484b8b4aa9248b6998b6222d62f5a77
Title: Kepler-186f
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('kepler186f/kepler186f.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.clouds} rotation={[Math.PI, -1.107, Math.PI]} scale={1.002} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.atmos} rotation={[Math.PI, -1.107, Math.PI]} scale={1.003} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.planet} rotation={[-Math.PI, -0.708, -Math.PI]} scale={0.981} />
    </group>
  )
}

useGLTF.preload('/kepler186f.gltf')
