/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 pegasi.gltf 
Author: uperesito (https://sketchfab.com/uperesito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/51-pegasi-b-359f9db593ae4c138702b4a58d96a963
Title: 51 Pegasi B
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('51PegasiB/pegasi.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Esfera_Mat_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Esfera_Mat_0_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Esfera_Mat_0_2.geometry} material={materials.material} />
          <mesh geometry={nodes.Esfera_Mat_0_3.geometry} material={materials.material} />
          <mesh geometry={nodes.Esfera_Mat_0_4.geometry} material={materials.material} />
          <mesh geometry={nodes.Esfera_Mat_0_5.geometry} material={materials.material} />
          <mesh geometry={nodes.Esfera_Mat_0_6.geometry} material={materials.material} />
          <mesh geometry={nodes.Esfera_Mat_0_7.geometry} material={materials.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pegasi.gltf')
