/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 kepler22b.gltf 
Author: per.rb1 (https://sketchfab.com/per.rb1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kepler-22b-3589154676b7465c815a4aa1d8c4354a
Title: Kepler 22b
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('kepler22b/kepler22b.gltf')
  return (
    <group {...props} dispose={null} scale={0.4, 0.4, 0.4}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} scale={[6.853, 6.999, 6.782]} />
    </group>
  )
}

useGLTF.preload('/kepler22b.gltf')
